import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F9FBFC",
  },
  darkContainer: {
    backgroundColor: "#0d0d0d",
  },
  topNav: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingTop: 50,
    paddingBottom: 16,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#EDF3FC",
  },
  darkTopNav: {
    backgroundColor: "#131313",
    borderBottomColor: "#2E3033",
  },
  messageActionIcon: {
    width: 24,
    height: 24,
  },
  centerSection: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 12,
  },
  communityImage: {
    width: 40,
    height: 40,
    borderRadius: 12,
  },
  title: {
    fontSize: 18,
    fontWeight: "500",
    fontFamily: "Satoshi",
    color: "#2D3C52",
  },
  darkTitle: {
    color: "#FFFFFF",
  },
  onlineStatus: {
    fontSize: 13,
    fontWeight: "400",
    color: "#61728C",
    fontFamily: "Satoshi",
    marginTop: 4,
  },
  darkOnlineStatus: {
    color: "#B3B3B3",
  },
  infoButton: {
    padding: 10,
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 50,
    backgroundColor: "#fff",
    borderWidth: 0.5,
    borderColor: "#EDF3FC",
  },
  darkInfoButton: {
    backgroundColor: "#131313",
    borderColor: "#2E3033",
  },
  infoIcon: {
    width: 20,
    height: 20,
    resizeMode: "contain",
  },
  messagesContainer: {
    flex: 1,
    backgroundColor: "#F9FBFC",
  },
  darkMessagesContainer: {
    backgroundColor: "#0d0d0d",
  },
  messagesContent: {
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  dateDivider: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    gap: 12,
  },
  dateDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#E2E8F0",
  },
  darkDateDividerLine: {
    backgroundColor: "#2e3033",
  },
  dateDividerText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#A0AEC0",
    fontFamily: "Satoshi",
  },
  darkDateDividerText: {
    color: "#b3b3b3",
  },
  messageWrapper: {
    marginBottom: 12,
  },
  otherUserMessageContainer: {
    flexDirection: "row",
    gap: 12,
    alignItems: "flex-start",
    justifyContent: "flex-start",
    width: "100%",
    marginBottom: 4,
  },
  userAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    flexShrink: 0,
  },
  userAvatarPlaceholder: {
    width: 32,
    height: 32,
    borderRadius: 16,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E8ECEF",
  },
  userAvatarPlaceholderDark: {
    backgroundColor: "#2A3942",
  },
  otherUserMessage: {
    maxWidth: "80%",
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
    borderBottomLeftRadius: 4,
    paddingVertical: 8,
    paddingHorizontal: 12,
    gap: 6,
    flexShrink: 1,
    flexGrow: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 2,
    elevation: 1,
  },
  darkOtherUserMessage: {
    backgroundColor: "#202C33",
    borderWidth: 0,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
    borderBottomLeftRadius: 4,
    shadowOpacity: 0,
    elevation: 0,
  },
  messageHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  userName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#2D3C52",
    fontFamily: "Satoshi",
  },
  darkUserName: {
    color: "#e0e0e0",
  },
  timestamp: {
    fontSize: 11,
    fontWeight: "400",
    color: "#A0AEC0",
    fontFamily: "Satoshi",
  },
  messageText: {
    fontSize: 14,
    fontWeight: "400",
    color: "#4A5568",
    fontFamily: "Satoshi",
    lineHeight: 20,
  },
  darkMessageText: {
    color: "#e0e0e0",
  },
  reactionsContainer: {
    marginTop: 6,
  },
  otherUserReactionsContainer: {
    paddingLeft: 44,
    marginTop: 6,
  },
  currentUserReactionsContainer: {
    paddingRight: 0,
    marginTop: 6,
    alignItems: "flex-end",
  },
  reactions: {
    flexDirection: "row",
    gap: 8,
  },
  reactionBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F7FAFC",
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    gap: 4,
    borderWidth: 0.5,
    borderColor: "#EDF3FC",
  },
  darkReactionBadge: {
    backgroundColor: "#131313",
    borderColor: "#2e3033",
  },
  reactionEmoji: {
    fontSize: 14,
  },
  reactionCount: {
    fontSize: 12,
    fontWeight: "500",
    color: "#4A5568",
    fontFamily: "Satoshi",
  },
  darkReactionCount: {
    color: "#b3b3b3",
  },
  messageActionButton: {
    padding: 4,
  },
  messageEmoji: {
    fontSize: 20,
  },
  currentUserMessageContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-end",
    width: "100%",
    marginBottom: 4,
  },
  currentUserMessage: {
    maxWidth: "80%",
    backgroundColor: "#DCF8C6",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 4,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 0,
  },
  darkCurrentUserMessage: {
    backgroundColor: "#005C4B",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 4,
    borderWidth: 0,
  },
  waCurrentUserTextLight: {
    fontSize: 14,
    fontWeight: "400",
    color: "#111B21",
    fontFamily: "Satoshi",
    lineHeight: 20,
  },
  waCurrentUserMentionLight: {
    fontWeight: "700",
    color: "#056162",
  },
  waCurrentUserTextDark: {
    fontSize: 14,
    fontWeight: "400",
    color: "#E9EDEF",
    fontFamily: "Satoshi",
    lineHeight: 20,
  },
  waCurrentUserMentionDark: {
    fontWeight: "700",
    color: "#9EE4D4",
  },
  tempMessage: {
    opacity: 0.7,
  },
  loadingMoreContainer: {
    paddingVertical: 16,
    alignItems: "center",
  },
  typingIndicatorContainer: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: "#F7FAFC",
    borderTopWidth: 1,
    borderTopColor: "#EDF3FC",
  },
  darkTypingIndicatorContainer: {
    backgroundColor: "#131313",
    borderTopColor: "#2e3033",
  },
  typingIndicatorText: {
    fontSize: 13,
    fontFamily: "Satoshi",
    color: "#61728C",
    fontStyle: "italic",
  },
  darkTypingIndicatorText: {
    color: "#B3B3B3",
  },
  currentUserMessageHeader: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  currentUserAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  currentUserInfo: {
    flex: 1,
  },
  userNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  currentUserName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#00FF80",
    fontFamily: "Satoshi",
  },
  verifiedBadge: {
    width: 16,
    height: 16,
  },
  modBadge: {
    backgroundColor: "#000000",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
    marginLeft: 4,
  },
  darkModBadge: {
    backgroundColor: "#00FF80",
  },
  modBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#00FF80",
    fontFamily: "Satoshi",
  },
  darkModBadgeText: {
    color: "#000000",
  },
  currentUserTimestamp: {
    fontSize: 11,
    fontWeight: "400",
    color: "#A0AEC0",
    fontFamily: "Satoshi",
  },
  currentUserMessageText: {
    fontSize: 14,
    fontWeight: "400",
    color: "#E9EDEF",
    fontFamily: "Satoshi",
    lineHeight: 20,
  },
  currentUserMentionText: {
    fontWeight: "700",
    color: "#9EE4D4",
  },
  messageMentionText: {
    fontWeight: "700",
  },
  darkMessageMentionText: {
    fontWeight: "700",
    color: "#00FF80",
  },
  mentionSuggestionWrap: {
    maxHeight: 200,
    marginHorizontal: 16,
    marginBottom: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#EDF3FC",
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
  },
  darkMentionSuggestionWrap: {
    backgroundColor: "#1a1a1a",
    borderColor: "#2E3033",
  },
  mentionSuggestionScroll: {
    maxHeight: 200,
  },
  mentionSuggestionRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#EDF3FC",
  },
  darkMentionSuggestionRow: {
    borderBottomColor: "#2E3033",
  },
  mentionSuggestionAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  mentionSuggestionTextCol: {
    flex: 1,
    minWidth: 0,
  },
  mentionSuggestionName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#2D3C52",
    fontFamily: "Satoshi",
  },
  darkMentionSuggestionName: {
    color: "#E0E0E0",
  },
  mentionSuggestionUser: {
    fontSize: 12,
    color: "#61728C",
    fontFamily: "Satoshi",
  },
  darkMentionSuggestionUser: {
    color: "#B3B3B3",
  },
  currentUserReactions: {
    flexDirection: "row",
    gap: 8,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 32,
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#EDF3FC",
    gap: 12,
  },
  darkInputContainer: {
    backgroundColor: "#131313",
    borderTopColor: "#2E3033",
  },
  emojiButton: {
    width: 36,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F9FBFC",
    borderWidth: 0.6,
    borderColor: "#EDF3FC",
    padding: 5.5,
    gap: 100,
  },
  emojiButtonText: {
    fontSize: 24,
  },
  input: {
    flex: 1,
    backgroundColor: "#F7FAFC",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 14,
    fontFamily: "Satoshi",
    color: "#61728C",
    height: 48,
    maxHeight: 100,
  },
  darkInput: {
    backgroundColor: "#0d0d0d",
    color: "#e0e0e0",
    borderWidth: 0.688,
    borderColor: "#2e3033",
  },
  sendButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  sendButtonDisabled: {
    opacity: 0.5,
  },
  centerContent: {
    justifyContent: "center",
    alignItems: "center",
    gap: 16,
  },
  loadingText: {
    fontFamily: "Satoshi",
    fontSize: 16,
    fontWeight: "500",
    color: "#2D3C52",
  },
  darkText: {
    color: "#E0E0E0",
  },
  errorText: {
    fontFamily: "Satoshi",
    fontSize: 16,
    fontWeight: "500",
    color: "#FF3B30",
    textAlign: "center",
  },
  backButton: {
    paddingVertical: 10,
    paddingHorizontal: 24,
    backgroundColor: "#000",
    borderRadius: 16,
    marginTop: 16,
  },
  backButtonText: {
    color: "#00FF80",
    fontFamily: "Satoshi",
    fontSize: 14,
    fontWeight: "600",
  },
  bottomSheetBackground: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  darkBottomSheetBackground: {
    backgroundColor: "#131313",
  },
  bottomSheetIndicator: {
    backgroundColor: "#EDF3FC",
    width: 40,
    height: 4,
  },
  darkBottomSheetIndicator: {
    backgroundColor: "#2e3033",
  },
  bottomSheetContent: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 32,
  },
  closeButton: {
    position: "absolute",
    top: 16,
    right: 24,
    zIndex: 10,
    padding: 4,
  },
  reactingToSection: {
    marginBottom: 24,
  },
  reactingToHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 12,
  },
  reactingToText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#61728C",
    fontFamily: "Satoshi",
  },
  darkReactingToText: {
    color: "#b3b3b3",
  },
  reactingToMessageBox: {
    backgroundColor: "#C8F4DD",
    borderRadius: 12,
    padding: 12,
  },
  darkReactingToMessageBox: {
    backgroundColor: "#131313",
    borderWidth: 1,
    borderColor: "#2e3033",
  },
  reactingToMessage: {
    fontSize: 13,
    fontWeight: "400",
    color: "#2D3C52",
    fontFamily: "Satoshi",
    lineHeight: 18,
  },
  darkReactingToMessage: {
    color: "#e0e0e0",
  },
  mentionText: {
    fontWeight: "600",
    color: "#2D3C52",
  },
  darkMentionText: {
    color: "#00FF80",
  },
  emojiReactionsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 32,
    paddingHorizontal: 8,
  },
  emojiReactionButton: {
    padding: 8,
  },
  emojiReaction: {
    fontSize: 32,
  },
  actionButtonsContainer: {
    gap: 16,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
  },
  actionButtonText: {
    fontSize: 15,
    fontWeight: "500",
    color: "#4A5568",
    fontFamily: "Satoshi",
  },
  darkActionButtonText: {
    color: "#b3b3b3",
  },
  actionButtonDanger: {},
  actionButtonTextDanger: {
    color: "#FF3B30",
  },
});
